name: GamesUI By MR Zinkil
main: PMPLUGINS\GamesUI\Main
version: 1.0.0
api: [3.0.0]
load: MR Zinkil 2020 COPYRIGHT
author: MR Zinkil
description: COPYRIGHT 2020 MR Zinkil
website: https://www.youtube.com/channel/UCM7WWOmQmD8b_fBWQmFxl8w

commands: 
 games:
    description: "GamesUI By MR Zinkil"
    usage: "/games"
 ginfo:
    description: " info GamesUI By MR Zinkil"
    usage: "/ginfo"
